#!/bin/bash
# PgBouncer environment variables
# Copyright Blackbox Tooling
# SPDX-License-Identifier: Apache-2.0

# Directories
export PGBOUNCER_BASE_DIR="/opt/blackbox/pgbouncer"
export PGBOUNCER_CONF_DIR="${PGBOUNCER_CONF_DIR:-/opt/blackbox/pgbouncer/conf}"
export PGBOUNCER_LOG_DIR="${PGBOUNCER_LOG_DIR:-/opt/blackbox/pgbouncer/logs}"
export PGBOUNCER_TMP_DIR="${PGBOUNCER_TMP_DIR:-/opt/blackbox/pgbouncer/tmp}"
export PGBOUNCER_CERTS_DIR="${PGBOUNCER_CERTS_DIR:-/opt/blackbox/pgbouncer/certs}"
export PGBOUNCER_MOUNTED_CONF_DIR="${PGBOUNCER_MOUNTED_CONF_DIR:-/opt/blackbox/pgbouncer/mounted-conf}"

# Files
export PGBOUNCER_CONF_FILE="${PGBOUNCER_CONF_DIR}/pgbouncer.ini"
export PGBOUNCER_AUTH_FILE="${PGBOUNCER_CONF_DIR}/userlist.txt"
export PGBOUNCER_PID_FILE="${PGBOUNCER_TMP_DIR}/pgbouncer.pid"
export PGBOUNCER_LOG_FILE="${PGBOUNCER_LOG_DIR}/pgbouncer.log"

# Connection settings
export PGBOUNCER_PORT="${PGBOUNCER_PORT:-6432}"
export PGBOUNCER_LISTEN_ADDRESS="${PGBOUNCER_LISTEN_ADDRESS:-0.0.0.0}"
export PGBOUNCER_DATABASE="${PGBOUNCER_DATABASE:-}"

# Authentication
export PGBOUNCER_AUTH_TYPE="${PGBOUNCER_AUTH_TYPE:-scram-sha-256}"
export PGBOUNCER_AUTH_USER="${PGBOUNCER_AUTH_USER:-}"
export PGBOUNCER_AUTH_QUERY="${PGBOUNCER_AUTH_QUERY:-}"
export PGBOUNCER_AUTH_HBA_FILE="${PGBOUNCER_AUTH_HBA_FILE:-}"
export PGBOUNCER_USERLIST="${PGBOUNCER_USERLIST:-}"

# Pool settings
export PGBOUNCER_POOL_MODE="${PGBOUNCER_POOL_MODE:-transaction}"
export PGBOUNCER_DEFAULT_POOL_SIZE="${PGBOUNCER_DEFAULT_POOL_SIZE:-20}"
export PGBOUNCER_MIN_POOL_SIZE="${PGBOUNCER_MIN_POOL_SIZE:-0}"
export PGBOUNCER_RESERVE_POOL_SIZE="${PGBOUNCER_RESERVE_POOL_SIZE:-0}"
export PGBOUNCER_RESERVE_POOL_TIMEOUT="${PGBOUNCER_RESERVE_POOL_TIMEOUT:-5}"
export PGBOUNCER_MAX_CLIENT_CONN="${PGBOUNCER_MAX_CLIENT_CONN:-100}"
export PGBOUNCER_MAX_DB_CONNECTIONS="${PGBOUNCER_MAX_DB_CONNECTIONS:-0}"
export PGBOUNCER_MAX_USER_CONNECTIONS="${PGBOUNCER_MAX_USER_CONNECTIONS:-0}"

# Timeout settings
export PGBOUNCER_QUERY_TIMEOUT="${PGBOUNCER_QUERY_TIMEOUT:-0}"
export PGBOUNCER_QUERY_WAIT_TIMEOUT="${PGBOUNCER_QUERY_WAIT_TIMEOUT:-120}"
export PGBOUNCER_CLIENT_IDLE_TIMEOUT="${PGBOUNCER_CLIENT_IDLE_TIMEOUT:-0}"
export PGBOUNCER_CLIENT_LOGIN_TIMEOUT="${PGBOUNCER_CLIENT_LOGIN_TIMEOUT:-60}"
export PGBOUNCER_SERVER_IDLE_TIMEOUT="${PGBOUNCER_SERVER_IDLE_TIMEOUT:-600}"
export PGBOUNCER_SERVER_LIFETIME="${PGBOUNCER_SERVER_LIFETIME:-3600}"
export PGBOUNCER_SERVER_CONNECT_TIMEOUT="${PGBOUNCER_SERVER_CONNECT_TIMEOUT:-15}"
export PGBOUNCER_SERVER_LOGIN_RETRY="${PGBOUNCER_SERVER_LOGIN_RETRY:-15}"
export PGBOUNCER_IDLE_TRANSACTION_TIMEOUT="${PGBOUNCER_IDLE_TRANSACTION_TIMEOUT:-0}"
export PGBOUNCER_CANCEL_WAIT_TIMEOUT="${PGBOUNCER_CANCEL_WAIT_TIMEOUT:-10}"

# Logging
export PGBOUNCER_LOG_CONNECTIONS="${PGBOUNCER_LOG_CONNECTIONS:-0}"
export PGBOUNCER_LOG_DISCONNECTIONS="${PGBOUNCER_LOG_DISCONNECTIONS:-0}"
export PGBOUNCER_LOG_POOLER_ERRORS="${PGBOUNCER_LOG_POOLER_ERRORS:-1}"
export PGBOUNCER_LOG_STATS="${PGBOUNCER_LOG_STATS:-1}"
export PGBOUNCER_STATS_PERIOD="${PGBOUNCER_STATS_PERIOD:-60}"
export PGBOUNCER_STATS_USERS="${PGBOUNCER_STATS_USERS:-}"
export PGBOUNCER_VERBOSE="${PGBOUNCER_VERBOSE:-0}"

# Advanced settings
export PGBOUNCER_SERVER_RESET_QUERY="${PGBOUNCER_SERVER_RESET_QUERY:-DISCARD ALL}"
export PGBOUNCER_SERVER_RESET_QUERY_ALWAYS="${PGBOUNCER_SERVER_RESET_QUERY_ALWAYS:-0}"
export PGBOUNCER_SERVER_CHECK_QUERY="${PGBOUNCER_SERVER_CHECK_QUERY:-select 1}"
export PGBOUNCER_SERVER_CHECK_DELAY="${PGBOUNCER_SERVER_CHECK_DELAY:-30}"
export PGBOUNCER_SERVER_FAST_CLOSE="${PGBOUNCER_SERVER_FAST_CLOSE:-0}"
export PGBOUNCER_SERVER_ROUND_ROBIN="${PGBOUNCER_SERVER_ROUND_ROBIN:-0}"
export PGBOUNCER_APPLICATION_NAME_ADD_HOST="${PGBOUNCER_APPLICATION_NAME_ADD_HOST:-0}"
export PGBOUNCER_IGNORE_STARTUP_PARAMETERS="${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:-extra_float_digits,options}"
export PGBOUNCER_DISABLE_PQEXEC="${PGBOUNCER_DISABLE_PQEXEC:-0}"
export PGBOUNCER_MAX_PREPARED_STATEMENTS="${PGBOUNCER_MAX_PREPARED_STATEMENTS:-0}"
export PGBOUNCER_SO_REUSEPORT="${PGBOUNCER_SO_REUSEPORT:-0}"
export PGBOUNCER_TCP_KEEPALIVE="${PGBOUNCER_TCP_KEEPALIVE:-1}"
export PGBOUNCER_TCP_KEEPCNT="${PGBOUNCER_TCP_KEEPCNT:-0}"
export PGBOUNCER_TCP_KEEPIDLE="${PGBOUNCER_TCP_KEEPIDLE:-0}"
export PGBOUNCER_TCP_KEEPINTVL="${PGBOUNCER_TCP_KEEPINTVL:-0}"
export PGBOUNCER_TCP_USER_TIMEOUT="${PGBOUNCER_TCP_USER_TIMEOUT:-0}"

# Client TLS
export PGBOUNCER_CLIENT_TLS_SSLMODE="${PGBOUNCER_CLIENT_TLS_SSLMODE:-disable}"
export PGBOUNCER_CLIENT_TLS_CERT_FILE="${PGBOUNCER_CLIENT_TLS_CERT_FILE:-}"
export PGBOUNCER_CLIENT_TLS_KEY_FILE="${PGBOUNCER_CLIENT_TLS_KEY_FILE:-}"
export PGBOUNCER_CLIENT_TLS_CA_FILE="${PGBOUNCER_CLIENT_TLS_CA_FILE:-}"
export PGBOUNCER_CLIENT_TLS_PROTOCOLS="${PGBOUNCER_CLIENT_TLS_PROTOCOLS:-secure}"
export PGBOUNCER_CLIENT_TLS_CIPHERS="${PGBOUNCER_CLIENT_TLS_CIPHERS:-fast}"
export PGBOUNCER_CLIENT_TLS_DHEPARAMS="${PGBOUNCER_CLIENT_TLS_DHEPARAMS:-auto}"
export PGBOUNCER_CLIENT_TLS_ECDHCURVE="${PGBOUNCER_CLIENT_TLS_ECDHCURVE:-auto}"

# Server TLS
export PGBOUNCER_SERVER_TLS_SSLMODE="${PGBOUNCER_SERVER_TLS_SSLMODE:-disable}"
export PGBOUNCER_SERVER_TLS_CERT_FILE="${PGBOUNCER_SERVER_TLS_CERT_FILE:-}"
export PGBOUNCER_SERVER_TLS_KEY_FILE="${PGBOUNCER_SERVER_TLS_KEY_FILE:-}"
export PGBOUNCER_SERVER_TLS_CA_FILE="${PGBOUNCER_SERVER_TLS_CA_FILE:-}"
export PGBOUNCER_SERVER_TLS_PROTOCOLS="${PGBOUNCER_SERVER_TLS_PROTOCOLS:-secure}"
export PGBOUNCER_SERVER_TLS_CIPHERS="${PGBOUNCER_SERVER_TLS_CIPHERS:-fast}"

# PostgreSQL backend defaults
export POSTGRESQL_HOST="${POSTGRESQL_HOST:-postgresql}"
export POSTGRESQL_PORT="${POSTGRESQL_PORT:-5432}"
export POSTGRESQL_USERNAME="${POSTGRESQL_USERNAME:-postgres}"
export POSTGRESQL_PASSWORD="${POSTGRESQL_PASSWORD:-}"
export POSTGRESQL_DATABASE="${POSTGRESQL_DATABASE:-postgres}"

# Init settings
export PGBOUNCER_INIT_SLEEP_TIME="${PGBOUNCER_INIT_SLEEP_TIME:-10}"
export PGBOUNCER_INIT_MAX_RETRIES="${PGBOUNCER_INIT_MAX_RETRIES:-10}"

# Extra flags
export PGBOUNCER_EXTRA_FLAGS="${PGBOUNCER_EXTRA_FLAGS:-}"

# Daemon settings
export PGBOUNCER_DAEMON_USER="blackbox"
export PGBOUNCER_DAEMON_GROUP="blackbox"
